apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-mlexecution-training
spec:
  entrypoint: python /home/ray/samples/sample_code.py
  runtimeEnvYAML: |
    pip:
      - torch
      - torchvision
      - tqdm
      - transformers
  clusterSelector:
    ray.io/cluster: test-ray-cluster
