apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator
spec:
  project: sandbox
  sources:
    - repoURL: https://github.com/ray-project/kuberay
      targetRevision: release-1.3
      path: helm-chart/kuberay-operator
      helm:
        skipCrds: true
        releaseName: kuberay-operator
        valueFiles:
          - $values/kuberay-operator/values.yaml
    - repoURL: https://github.com/TeckResources/da-hackathon-ray-server
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kuberay-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuberay-operator-crds
spec:
  project: sandbox
  source:
    repoURL: https://github.com/ray-project/kuberay
    targetRevision: release-1.3
    path: helm-chart/kuberay-operator/crds
  destination:
    server: https://kubernetes.default.svc
    namespace: kuberay-operator
  syncPolicy:
    syncOptions:
    - Replace=true

