apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hackathon-ray-server-app
  namespace: argo-cd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sandbox
  source:
    path: ray-server-infra
    repoURL: https://github.com/TeckResources/da-hackathon-ray-server
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sandbox-hackathon-ray-server
  ignoreDifferences:
  - group: ray.io
    kind: RayJob
    jqPathExpressions:
    - .spec.rayClusterSpec.workerGroupSpecs
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        da-project: sandbox
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Prune=confirm
    retry:
      limit: -1 # Unlimited
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
